version: '3.4'

services:
  projektnotatek:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ./certyfikaty/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./certyfikaty/Https:/root/.aspnet/https:ro